version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apk update
      - apk add python python-dev python
      - apk add --no-cache py-pip
      - python -v
      - pip -v
      - pip install awscli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t learnawsops .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo Invoking Lambda...
